apiVersion: v1
kind: Service
metadata:
  purpose: nginx-lb
  labels:
    purpose: service-lb-demo
spec: 

  type: LoadBalancer
  selector:
    purpose: deploy-demo
    project: roboshop
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.service.targetPort }}




