apiVersion: v1
kind: Service
metadata:
  purpose: nginx-lb
  labels:
    purpose: service-lb-demo
spec: 

  type: LoadBalancer
  metadata:
    selector:
      purpose: deployment-demo
      project: roboshop
      app: nginx
    ports:
      - protocol: TCP
        port: 80
        targetPort: {{ .Values.deployment.targetPort }}




